[package]
name = "mimir_mel"
version = "1.0.0"
edition = "2021"
description = "Mimir Encrypted Launcher (MEL)"
license = "GPL-3.0-only"
repository = "https://github.com/Offline-Program/MEL"
authors = [
    "Michael Clayton <mclayton@redhat.com>",
    "Jared Sprague <jsprague@redhat.com>",
]
publish = false

[[bin]]
name = "mel"
path = "src/main.rs"

[dependencies]
mel_libs = { path = "../mel_libs/" }
mimcp = { path = "../mimcp/" }
tar = "0.4.45"
flate2 = "1.0.33"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
tokio-util = "0.7"
axum = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter"] }
url = "2.5"
reqwest = "0.13"

[build-dependencies]
mel_libs = { path = "../mel_libs/" }
