[package]
name = "mimir_mel"
version = "1.0.0"
edition = "2021"
description = "Mimir Encrypted Launcher (MEL)"
license = "GPL-3.0-only"
repository = "https://github.com/Offline-Program/MEL"
authors = [
    "Michael Clayton <mclayton@redhat.com>",
    "Jared Sprague <jsprague@redhat.com>",
]
publish = false

[[bin]]
name = "mel"
path = "src/main.rs"

[dependencies]
mel_libs = { path = "../mel_libs/" }
tar = "0.4.41"
flate2 = "1.0.33"
axum = "0.8"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
mime_guess = "2"
bytes = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
openssl = "0.10"
minijinja = { version = "2", features = ["custom_syntax", "loader"] }

[build-dependencies]
mel_libs = { path = "../mel_libs/" }
